version: '3.8'
services:
  go:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: 'tail -f /dev/null'
    volumes:
      - ./:/go/app
      - node_modules:/go/app/node_modules
    environment:
      DEPLOY_STAGE: ${DEPLOY_STAGE}
      REGION: ${REGION}
      AWS_PROFILE: ${AWS_PROFILE}
volumes:
  node_modules:
    driver: 'local'
